
SET(PHYSFS_SEARCH_PATHS
    ${POLYCODE_RELEASE_DIR}/Framework/Core/Dependencies/lib
    ${POLYCODE_RELEASE_DIR}/Framework/Core/Dependencies/include
    ${POLYCODE_RELEASE_DIR}/Framework/Modules/Dependencies/lib
    )

SET(MSVC_YEAR_NAME)
IF(MSVC_VERSION GREATER 1599) # >= 1600
    SET(MSVC_YEAR_NAME VS2010)
ELSEIF(MSVC_VERSION GREATER 1499) # >= 1500
    SET(MSVC_YEAR_NAME VS2008)
ELSEIF(MSVC_VERSION GREATER 1399)
    SET(MSVC_YEAR_NAME VS2005)
ELSEIF(MSVC_VERSION GREATER 1299)
    SET(MSVC_YEAR_NAME VS2003)
ELSEIF(MSVC_VERSION GREATER 1199)
    SET(MSVC_YEAR_NAME VS6)
ENDIF()

FIND_PATH(PHYSFS_INCLUDE_DIR
    NAMES physfs.h
    HINTS
    $ENV{PHYSFSDIR}
    $ENV{PHYSFS_PATH}
    PATH_SUFFIXES include
    PATHS ${PHYSFS_SEARCH_PATHS}
    )

FIND_LIBRARY(PHYSFS_LIBRARY
    NAMES libphysfs physfs #NAMES wants more than one name or it fails. Weird.
    HINTS
    NO_DEFAULT_PATH
    NO_CMAKE_ENVIRONMENT_PATH
    NO_SYSTEM_ENVIRONMENT_PATH
    NO_CMAKE_PATH
    NO_CMAKE_SYSTEM_PATH
    $ENV{PHYSFSDIR}
    $ENV{PHYSFS_PATH}
    PATH_SUFFIXES lib lib64 "Win32/${MSVC_YEAR_NAME}/x64/Release" "Win32/${MSVC_YEAR_NAME}/Win32/Release"
    PATHS ${PHYSFS_SEARCH_PATHS}
    )

FIND_LIBRARY(PHYSFS_LIBRARY_DEBUG
    NAMES libphysfsd libphysfs_d physfsd physfs_d
    HINTS
    NO_DEFAULT_PATH
    NO_CMAKE_ENVIRONMENT_PATH
    NO_CMAKE_SYSTEM_PATH
    NO_SYSTEM_ENVIRONMENT_PATH
    NO_CMAKE_PATH
    $ENV{PHYSFSDIR}
    $ENV{PHYSFS_PATH}
    PATH_SUFFIXES lib lib64 "Win32/${MSVC_YEAR_NAME}/x64/Debug" "Win32/${MSVC_YEAR_NAME}/Win32/Debug"
    PATHS ${PHYSFS_SEARCH_PATHS}
    )

#I'm not really sure that this is needed.
#IF(NOT PHYSFS_LIBRARY_DEBUG)
#	MESSAGE("STILL CANT FIND PHYSFS_LIBRARY_DEBUG - ATTEMPTING TO SEARECH NON-SUFFIXED LIBRARIES")
#    FIND_LIBRARY(PHYSFS_LIBRARY_DEBUG
#        NAMES libphysfsd libphysfs_d
#        HINTS
#        NO_DEFAULT_PATH
#        NO_CMAKE_ENVIRONMENT_PATH
#        NO_CMAKE_SYSTEM_PATH
#        NO_SYSTEM_ENVIRONMENT_PATH
#        NO_CMAKE_PATH
#        CMAKE_FIND_FRAMEWORK NEVER
#        $ENV{PHYSFSDIR}
#        $ENV{PHYSFS_PATH}
#        PATH_SUFFIXES "Win32/${MSVC_YEAR_NAME}/x64/Debug" "Win32/${MSVC_YEAR_NAME}/Win32/Debug"
#        PATHS ${PHYSFS_SEARCH_PATHS}
#        )
#ENDIF()

IF(PHYSFS_LIBRARY)
    IF(PHYSFS_LIBRARY_DEBUG)
        SET(PHYSFS_LIBRARIES optimized "${PHYSFS_LIBRARY}" debug "${PHYSFS_LIBRARY_DEBUG}")
    ELSE()
        SET(PHYSFS_LIBRARIES "${PHYSFS_LIBRARY}")
    ENDIF()
ELSEIF(PHYSFS_LIBRARY_DEBUG)
    SET(PHYSFS_LIBRARIES debug "${PHYSFS_LIBRARY_DEBUG}")
ENDIF()

# handle the QUIETLY and REQUIRED arguments and set XXX_FOUND to TRUE if all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PHYSFS DEFAULT_MSG PHYSFS_LIBRARIES PHYSFS_INCLUDE_DIR)
